#version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appdock_app
    restart: unless-stopped
    working_dir: /var/www/appdock
    volumes:
      - ./src/appdock:/var/www
    ports:
      - "1001:9000"
    networks:
      - laravel
    depends_on:
      - db

  composer:
    image: composer:latest
    volumes:
      - ./src:/app
    working_dir: /app

  webserver:
    image: nginx:alpine
    container_name: appdock_nginx
    restart: unless-stopped
    ports:
      - "1002:80"
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mariadb:latest
    container_name: appdock_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "1003:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: appdock_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - "1004:80"
    networks:
      - laravel
 #adminer
  adminer:
    image: adminer
    container_name: appdock_adminer
    restart: unless-stopped
    tty: true
    ports:
      - 1005:8080
    environment:
      PMA_HOST: db
    networks:
      - laravel
networks:
  laravel:
    driver: bridge

volumes:
  mariadb_data:
